name: Newman Tests

on:
  workflow_dispatch:   # Allows manual trigger
  push:                # Optional: Runs on every push
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo code so that Newman can access your files
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js (required to run Newman)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # You can change to another LTS if needed

      # Step 3: Install Newman and Newman HTML reporter globally
      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      # Debugger step to list repo files
      - name: List files in repo
        run: ls -R

      # Step 4: Run your Postman collection using Newman
      - name: Run Newman Collection
        run: |
           newman run "Demo collection.json" \
           -e "Demo environment.postman_environment.json" \
           -r cli,json,html \
           --reporter-json-export results.json \
           --reporter-html-export report.html
